/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.pongi;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.example.gradle.db.pongi.tables.Scorecord;
import org.jooq.example.gradle.db.pongi.tables.Userscore;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pongi extends SchemaImpl {

	private static final long serialVersionUID = 1239274948;

	/**
	 * The reference instance of <code>pongi</code>
	 */
	public static final Pongi PONGI = new Pongi();

	/**
	 * No further instances allowed
	 */
	private Pongi() {
		super("pongi");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Scorecord.SCORECORD,
			Userscore.USERSCORE);
	}
}
