/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.pongi;


import javax.annotation.Generated;

import org.jooq.example.gradle.db.pongi.tables.Scorecord;
import org.jooq.example.gradle.db.pongi.tables.Userscore;


/**
 * Convenience access to all tables in pongi
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table pongi.SCORECORD
	 */
	public static final Scorecord SCORECORD = org.jooq.example.gradle.db.pongi.tables.Scorecord.SCORECORD;

	/**
	 * The table pongi.USERSCORE
	 */
	public static final Userscore USERSCORE = org.jooq.example.gradle.db.pongi.tables.Userscore.USERSCORE;
}
