/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.pongi.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Scorecord implements Serializable {

	private static final long serialVersionUID = 1831427824;

	private String  user;
	private Byte    won;
	private Integer scoredpoint;
	private Integer lostpoint;
	private String  gameid;

	public Scorecord() {}

	public Scorecord(Scorecord value) {
		this.user = value.user;
		this.won = value.won;
		this.scoredpoint = value.scoredpoint;
		this.lostpoint = value.lostpoint;
		this.gameid = value.gameid;
	}

	public Scorecord(
		String  user,
		Byte    won,
		Integer scoredpoint,
		Integer lostpoint,
		String  gameid
	) {
		this.user = user;
		this.won = won;
		this.scoredpoint = scoredpoint;
		this.lostpoint = lostpoint;
		this.gameid = gameid;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public Byte getWon() {
		return this.won;
	}

	public void setWon(Byte won) {
		this.won = won;
	}

	public Integer getScoredpoint() {
		return this.scoredpoint;
	}

	public void setScoredpoint(Integer scoredpoint) {
		this.scoredpoint = scoredpoint;
	}

	public Integer getLostpoint() {
		return this.lostpoint;
	}

	public void setLostpoint(Integer lostpoint) {
		this.lostpoint = lostpoint;
	}

	public String getGameid() {
		return this.gameid;
	}

	public void setGameid(String gameid) {
		this.gameid = gameid;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Scorecord (");

		sb.append(user);
		sb.append(", ").append(won);
		sb.append(", ").append(scoredpoint);
		sb.append(", ").append(lostpoint);
		sb.append(", ").append(gameid);

		sb.append(")");
		return sb.toString();
	}
}
