/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.pongi.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userscore implements Serializable {

	private static final long serialVersionUID = 1185780685;

	private String  user;
	private Integer won;
	private Integer lost;
	private Integer played;
	private Integer scoredpoint;
	private Integer lostpoint;

	public Userscore() {}

	public Userscore(Userscore value) {
		this.user = value.user;
		this.won = value.won;
		this.lost = value.lost;
		this.played = value.played;
		this.scoredpoint = value.scoredpoint;
		this.lostpoint = value.lostpoint;
	}

	public Userscore(
		String  user,
		Integer won,
		Integer lost,
		Integer played,
		Integer scoredpoint,
		Integer lostpoint
	) {
		this.user = user;
		this.won = won;
		this.lost = lost;
		this.played = played;
		this.scoredpoint = scoredpoint;
		this.lostpoint = lostpoint;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public Integer getWon() {
		return this.won;
	}

	public void setWon(Integer won) {
		this.won = won;
	}

	public Integer getLost() {
		return this.lost;
	}

	public void setLost(Integer lost) {
		this.lost = lost;
	}

	public Integer getPlayed() {
		return this.played;
	}

	public void setPlayed(Integer played) {
		this.played = played;
	}

	public Integer getScoredpoint() {
		return this.scoredpoint;
	}

	public void setScoredpoint(Integer scoredpoint) {
		this.scoredpoint = scoredpoint;
	}

	public Integer getLostpoint() {
		return this.lostpoint;
	}

	public void setLostpoint(Integer lostpoint) {
		this.lostpoint = lostpoint;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Userscore (");

		sb.append(user);
		sb.append(", ").append(won);
		sb.append(", ").append(lost);
		sb.append(", ").append(played);
		sb.append(", ").append(scoredpoint);
		sb.append(", ").append(lostpoint);

		sb.append(")");
		return sb.toString();
	}
}
