/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.example.gradle.db.information_schema.tables.CharacterSets;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterSetsRecord extends TableRecordImpl<CharacterSetsRecord> implements Record4<String, String, String, Long> {

	private static final long serialVersionUID = 519461364;

	/**
	 * Setter for <code>information_schema.CHARACTER_SETS.CHARACTER_SET_NAME</code>.
	 */
	public void setCharacterSetName(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>information_schema.CHARACTER_SETS.CHARACTER_SET_NAME</code>.
	 */
	public String getCharacterSetName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>information_schema.CHARACTER_SETS.DEFAULT_COLLATE_NAME</code>.
	 */
	public void setDefaultCollateName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>information_schema.CHARACTER_SETS.DEFAULT_COLLATE_NAME</code>.
	 */
	public String getDefaultCollateName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>information_schema.CHARACTER_SETS.DESCRIPTION</code>.
	 */
	public void setDescription(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>information_schema.CHARACTER_SETS.DESCRIPTION</code>.
	 */
	public String getDescription() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>information_schema.CHARACTER_SETS.MAXLEN</code>.
	 */
	public void setMaxlen(Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>information_schema.CHARACTER_SETS.MAXLEN</code>.
	 */
	public Long getMaxlen() {
		return (Long) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<String, String, String, Long> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<String, String, String, Long> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return CharacterSets.CHARACTER_SETS.CHARACTER_SET_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return CharacterSets.CHARACTER_SETS.DEFAULT_COLLATE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return CharacterSets.CHARACTER_SETS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return CharacterSets.CHARACTER_SETS.MAXLEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getCharacterSetName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDefaultCollateName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getMaxlen();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CharacterSetsRecord value1(String value) {
		setCharacterSetName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CharacterSetsRecord value2(String value) {
		setDefaultCollateName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CharacterSetsRecord value3(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CharacterSetsRecord value4(Long value) {
		setMaxlen(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CharacterSetsRecord values(String value1, String value2, String value3, Long value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CharacterSetsRecord
	 */
	public CharacterSetsRecord() {
		super(CharacterSets.CHARACTER_SETS);
	}

	/**
	 * Create a detached, initialised CharacterSetsRecord
	 */
	public CharacterSetsRecord(String characterSetName, String defaultCollateName, String description, Long maxlen) {
		super(CharacterSets.CHARACTER_SETS);

		setValue(0, characterSetName);
		setValue(1, defaultCollateName);
		setValue(2, description);
		setValue(3, maxlen);
	}
}
