/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.example.gradle.db.information_schema.tables.Partitions;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartitionsRecord extends TableRecordImpl<PartitionsRecord> {

	private static final long serialVersionUID = -143409228;

	/**
	 * Setter for <code>information_schema.PARTITIONS.TABLE_CATALOG</code>.
	 */
	public void setTableCatalog(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.TABLE_CATALOG</code>.
	 */
	public String getTableCatalog() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.TABLE_SCHEMA</code>.
	 */
	public void setTableSchema(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.TABLE_SCHEMA</code>.
	 */
	public String getTableSchema() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.TABLE_NAME</code>.
	 */
	public void setTableName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.TABLE_NAME</code>.
	 */
	public String getTableName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.PARTITION_NAME</code>.
	 */
	public void setPartitionName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.PARTITION_NAME</code>.
	 */
	public String getPartitionName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.SUBPARTITION_NAME</code>.
	 */
	public void setSubpartitionName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.SUBPARTITION_NAME</code>.
	 */
	public String getSubpartitionName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.PARTITION_ORDINAL_POSITION</code>.
	 */
	public void setPartitionOrdinalPosition(ULong value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.PARTITION_ORDINAL_POSITION</code>.
	 */
	public ULong getPartitionOrdinalPosition() {
		return (ULong) getValue(5);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.SUBPARTITION_ORDINAL_POSITION</code>.
	 */
	public void setSubpartitionOrdinalPosition(ULong value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.SUBPARTITION_ORDINAL_POSITION</code>.
	 */
	public ULong getSubpartitionOrdinalPosition() {
		return (ULong) getValue(6);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.PARTITION_METHOD</code>.
	 */
	public void setPartitionMethod(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.PARTITION_METHOD</code>.
	 */
	public String getPartitionMethod() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.SUBPARTITION_METHOD</code>.
	 */
	public void setSubpartitionMethod(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.SUBPARTITION_METHOD</code>.
	 */
	public String getSubpartitionMethod() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.PARTITION_EXPRESSION</code>.
	 */
	public void setPartitionExpression(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.PARTITION_EXPRESSION</code>.
	 */
	public String getPartitionExpression() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.SUBPARTITION_EXPRESSION</code>.
	 */
	public void setSubpartitionExpression(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.SUBPARTITION_EXPRESSION</code>.
	 */
	public String getSubpartitionExpression() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.PARTITION_DESCRIPTION</code>.
	 */
	public void setPartitionDescription(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.PARTITION_DESCRIPTION</code>.
	 */
	public String getPartitionDescription() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.TABLE_ROWS</code>.
	 */
	public void setTableRows(ULong value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.TABLE_ROWS</code>.
	 */
	public ULong getTableRows() {
		return (ULong) getValue(12);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.AVG_ROW_LENGTH</code>.
	 */
	public void setAvgRowLength(ULong value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.AVG_ROW_LENGTH</code>.
	 */
	public ULong getAvgRowLength() {
		return (ULong) getValue(13);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.DATA_LENGTH</code>.
	 */
	public void setDataLength(ULong value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.DATA_LENGTH</code>.
	 */
	public ULong getDataLength() {
		return (ULong) getValue(14);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.MAX_DATA_LENGTH</code>.
	 */
	public void setMaxDataLength(ULong value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.MAX_DATA_LENGTH</code>.
	 */
	public ULong getMaxDataLength() {
		return (ULong) getValue(15);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.INDEX_LENGTH</code>.
	 */
	public void setIndexLength(ULong value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.INDEX_LENGTH</code>.
	 */
	public ULong getIndexLength() {
		return (ULong) getValue(16);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.DATA_FREE</code>.
	 */
	public void setDataFree(ULong value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.DATA_FREE</code>.
	 */
	public ULong getDataFree() {
		return (ULong) getValue(17);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.CREATE_TIME</code>.
	 */
	public void setCreateTime(Timestamp value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.CREATE_TIME</code>.
	 */
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(18);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.UPDATE_TIME</code>.
	 */
	public void setUpdateTime(Timestamp value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.UPDATE_TIME</code>.
	 */
	public Timestamp getUpdateTime() {
		return (Timestamp) getValue(19);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.CHECK_TIME</code>.
	 */
	public void setCheckTime(Timestamp value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.CHECK_TIME</code>.
	 */
	public Timestamp getCheckTime() {
		return (Timestamp) getValue(20);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.CHECKSUM</code>.
	 */
	public void setChecksum(ULong value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.CHECKSUM</code>.
	 */
	public ULong getChecksum() {
		return (ULong) getValue(21);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.PARTITION_COMMENT</code>.
	 */
	public void setPartitionComment(String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.PARTITION_COMMENT</code>.
	 */
	public String getPartitionComment() {
		return (String) getValue(22);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.NODEGROUP</code>.
	 */
	public void setNodegroup(String value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.NODEGROUP</code>.
	 */
	public String getNodegroup() {
		return (String) getValue(23);
	}

	/**
	 * Setter for <code>information_schema.PARTITIONS.TABLESPACE_NAME</code>.
	 */
	public void setTablespaceName(String value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>information_schema.PARTITIONS.TABLESPACE_NAME</code>.
	 */
	public String getTablespaceName() {
		return (String) getValue(24);
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PartitionsRecord
	 */
	public PartitionsRecord() {
		super(Partitions.PARTITIONS);
	}

	/**
	 * Create a detached, initialised PartitionsRecord
	 */
	public PartitionsRecord(String tableCatalog, String tableSchema, String tableName, String partitionName, String subpartitionName, ULong partitionOrdinalPosition, ULong subpartitionOrdinalPosition, String partitionMethod, String subpartitionMethod, String partitionExpression, String subpartitionExpression, String partitionDescription, ULong tableRows, ULong avgRowLength, ULong dataLength, ULong maxDataLength, ULong indexLength, ULong dataFree, Timestamp createTime, Timestamp updateTime, Timestamp checkTime, ULong checksum, String partitionComment, String nodegroup, String tablespaceName) {
		super(Partitions.PARTITIONS);

		setValue(0, tableCatalog);
		setValue(1, tableSchema);
		setValue(2, tableName);
		setValue(3, partitionName);
		setValue(4, subpartitionName);
		setValue(5, partitionOrdinalPosition);
		setValue(6, subpartitionOrdinalPosition);
		setValue(7, partitionMethod);
		setValue(8, subpartitionMethod);
		setValue(9, partitionExpression);
		setValue(10, subpartitionExpression);
		setValue(11, partitionDescription);
		setValue(12, tableRows);
		setValue(13, avgRowLength);
		setValue(14, dataLength);
		setValue(15, maxDataLength);
		setValue(16, indexLength);
		setValue(17, dataFree);
		setValue(18, createTime);
		setValue(19, updateTime);
		setValue(20, checkTime);
		setValue(21, checksum);
		setValue(22, partitionComment);
		setValue(23, nodegroup);
		setValue(24, tablespaceName);
	}
}
