/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.example.gradle.db.information_schema.tables.Profiling;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfilingRecord extends TableRecordImpl<ProfilingRecord> implements Record18<Integer, Integer, String, BigDecimal, BigDecimal, BigDecimal, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String, Integer> {

	private static final long serialVersionUID = 661618631;

	/**
	 * Setter for <code>information_schema.PROFILING.QUERY_ID</code>.
	 */
	public void setQueryId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.QUERY_ID</code>.
	 */
	public Integer getQueryId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.SEQ</code>.
	 */
	public void setSeq(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.SEQ</code>.
	 */
	public Integer getSeq() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.STATE</code>.
	 */
	public void setState(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.STATE</code>.
	 */
	public String getState() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.DURATION</code>.
	 */
	public void setDuration(BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.DURATION</code>.
	 */
	public BigDecimal getDuration() {
		return (BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.CPU_USER</code>.
	 */
	public void setCpuUser(BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.CPU_USER</code>.
	 */
	public BigDecimal getCpuUser() {
		return (BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.CPU_SYSTEM</code>.
	 */
	public void setCpuSystem(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.CPU_SYSTEM</code>.
	 */
	public BigDecimal getCpuSystem() {
		return (BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.CONTEXT_VOLUNTARY</code>.
	 */
	public void setContextVoluntary(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.CONTEXT_VOLUNTARY</code>.
	 */
	public Integer getContextVoluntary() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.CONTEXT_INVOLUNTARY</code>.
	 */
	public void setContextInvoluntary(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.CONTEXT_INVOLUNTARY</code>.
	 */
	public Integer getContextInvoluntary() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.BLOCK_OPS_IN</code>.
	 */
	public void setBlockOpsIn(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.BLOCK_OPS_IN</code>.
	 */
	public Integer getBlockOpsIn() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.BLOCK_OPS_OUT</code>.
	 */
	public void setBlockOpsOut(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.BLOCK_OPS_OUT</code>.
	 */
	public Integer getBlockOpsOut() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.MESSAGES_SENT</code>.
	 */
	public void setMessagesSent(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.MESSAGES_SENT</code>.
	 */
	public Integer getMessagesSent() {
		return (Integer) getValue(10);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.MESSAGES_RECEIVED</code>.
	 */
	public void setMessagesReceived(Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.MESSAGES_RECEIVED</code>.
	 */
	public Integer getMessagesReceived() {
		return (Integer) getValue(11);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.PAGE_FAULTS_MAJOR</code>.
	 */
	public void setPageFaultsMajor(Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.PAGE_FAULTS_MAJOR</code>.
	 */
	public Integer getPageFaultsMajor() {
		return (Integer) getValue(12);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.PAGE_FAULTS_MINOR</code>.
	 */
	public void setPageFaultsMinor(Integer value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.PAGE_FAULTS_MINOR</code>.
	 */
	public Integer getPageFaultsMinor() {
		return (Integer) getValue(13);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.SWAPS</code>.
	 */
	public void setSwaps(Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.SWAPS</code>.
	 */
	public Integer getSwaps() {
		return (Integer) getValue(14);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.SOURCE_FUNCTION</code>.
	 */
	public void setSourceFunction(String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.SOURCE_FUNCTION</code>.
	 */
	public String getSourceFunction() {
		return (String) getValue(15);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.SOURCE_FILE</code>.
	 */
	public void setSourceFile(String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.SOURCE_FILE</code>.
	 */
	public String getSourceFile() {
		return (String) getValue(16);
	}

	/**
	 * Setter for <code>information_schema.PROFILING.SOURCE_LINE</code>.
	 */
	public void setSourceLine(Integer value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>information_schema.PROFILING.SOURCE_LINE</code>.
	 */
	public Integer getSourceLine() {
		return (Integer) getValue(17);
	}

	// -------------------------------------------------------------------------
	// Record18 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row18<Integer, Integer, String, BigDecimal, BigDecimal, BigDecimal, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String, Integer> fieldsRow() {
		return (Row18) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row18<Integer, Integer, String, BigDecimal, BigDecimal, BigDecimal, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String, Integer> valuesRow() {
		return (Row18) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Profiling.PROFILING.QUERY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Profiling.PROFILING.SEQ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Profiling.PROFILING.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field4() {
		return Profiling.PROFILING.DURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field5() {
		return Profiling.PROFILING.CPU_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field6() {
		return Profiling.PROFILING.CPU_SYSTEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Profiling.PROFILING.CONTEXT_VOLUNTARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Profiling.PROFILING.CONTEXT_INVOLUNTARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return Profiling.PROFILING.BLOCK_OPS_IN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return Profiling.PROFILING.BLOCK_OPS_OUT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return Profiling.PROFILING.MESSAGES_SENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field12() {
		return Profiling.PROFILING.MESSAGES_RECEIVED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field13() {
		return Profiling.PROFILING.PAGE_FAULTS_MAJOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field14() {
		return Profiling.PROFILING.PAGE_FAULTS_MINOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field15() {
		return Profiling.PROFILING.SWAPS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field16() {
		return Profiling.PROFILING.SOURCE_FUNCTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field17() {
		return Profiling.PROFILING.SOURCE_FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field18() {
		return Profiling.PROFILING.SOURCE_LINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getQueryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getSeq();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value4() {
		return getDuration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value5() {
		return getCpuUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value6() {
		return getCpuSystem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getContextVoluntary();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getContextInvoluntary();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getBlockOpsIn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getBlockOpsOut();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getMessagesSent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value12() {
		return getMessagesReceived();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value13() {
		return getPageFaultsMajor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value14() {
		return getPageFaultsMinor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value15() {
		return getSwaps();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value16() {
		return getSourceFunction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value17() {
		return getSourceFile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value18() {
		return getSourceLine();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value1(Integer value) {
		setQueryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value2(Integer value) {
		setSeq(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value3(String value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value4(BigDecimal value) {
		setDuration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value5(BigDecimal value) {
		setCpuUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value6(BigDecimal value) {
		setCpuSystem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value7(Integer value) {
		setContextVoluntary(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value8(Integer value) {
		setContextInvoluntary(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value9(Integer value) {
		setBlockOpsIn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value10(Integer value) {
		setBlockOpsOut(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value11(Integer value) {
		setMessagesSent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value12(Integer value) {
		setMessagesReceived(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value13(Integer value) {
		setPageFaultsMajor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value14(Integer value) {
		setPageFaultsMinor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value15(Integer value) {
		setSwaps(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value16(String value) {
		setSourceFunction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value17(String value) {
		setSourceFile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord value18(Integer value) {
		setSourceLine(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfilingRecord values(Integer value1, Integer value2, String value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, Integer value7, Integer value8, Integer value9, Integer value10, Integer value11, Integer value12, Integer value13, Integer value14, Integer value15, String value16, String value17, Integer value18) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		value17(value17);
		value18(value18);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProfilingRecord
	 */
	public ProfilingRecord() {
		super(Profiling.PROFILING);
	}

	/**
	 * Create a detached, initialised ProfilingRecord
	 */
	public ProfilingRecord(Integer queryId, Integer seq, String state, BigDecimal duration, BigDecimal cpuUser, BigDecimal cpuSystem, Integer contextVoluntary, Integer contextInvoluntary, Integer blockOpsIn, Integer blockOpsOut, Integer messagesSent, Integer messagesReceived, Integer pageFaultsMajor, Integer pageFaultsMinor, Integer swaps, String sourceFunction, String sourceFile, Integer sourceLine) {
		super(Profiling.PROFILING);

		setValue(0, queryId);
		setValue(1, seq);
		setValue(2, state);
		setValue(3, duration);
		setValue(4, cpuUser);
		setValue(5, cpuSystem);
		setValue(6, contextVoluntary);
		setValue(7, contextInvoluntary);
		setValue(8, blockOpsIn);
		setValue(9, blockOpsOut);
		setValue(10, messagesSent);
		setValue(11, messagesReceived);
		setValue(12, pageFaultsMajor);
		setValue(13, pageFaultsMinor);
		setValue(14, swaps);
		setValue(15, sourceFunction);
		setValue(16, sourceFile);
		setValue(17, sourceLine);
	}
}
