/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.example.gradle.db.information_schema.tables.Routines;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutinesRecord extends TableRecordImpl<RoutinesRecord> {

	private static final long serialVersionUID = 563963452;

	/**
	 * Setter for <code>information_schema.ROUTINES.SPECIFIC_NAME</code>.
	 */
	public void setSpecificName(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.SPECIFIC_NAME</code>.
	 */
	public String getSpecificName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.ROUTINE_CATALOG</code>.
	 */
	public void setRoutineCatalog(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.ROUTINE_CATALOG</code>.
	 */
	public String getRoutineCatalog() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.ROUTINE_SCHEMA</code>.
	 */
	public void setRoutineSchema(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.ROUTINE_SCHEMA</code>.
	 */
	public String getRoutineSchema() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.ROUTINE_NAME</code>.
	 */
	public void setRoutineName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.ROUTINE_NAME</code>.
	 */
	public String getRoutineName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.ROUTINE_TYPE</code>.
	 */
	public void setRoutineType(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.ROUTINE_TYPE</code>.
	 */
	public String getRoutineType() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.DATA_TYPE</code>.
	 */
	public void setDataType(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.DATA_TYPE</code>.
	 */
	public String getDataType() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.CHARACTER_MAXIMUM_LENGTH</code>.
	 */
	public void setCharacterMaximumLength(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.CHARACTER_MAXIMUM_LENGTH</code>.
	 */
	public Integer getCharacterMaximumLength() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.CHARACTER_OCTET_LENGTH</code>.
	 */
	public void setCharacterOctetLength(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.CHARACTER_OCTET_LENGTH</code>.
	 */
	public Integer getCharacterOctetLength() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.NUMERIC_PRECISION</code>.
	 */
	public void setNumericPrecision(ULong value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.NUMERIC_PRECISION</code>.
	 */
	public ULong getNumericPrecision() {
		return (ULong) getValue(8);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.NUMERIC_SCALE</code>.
	 */
	public void setNumericScale(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.NUMERIC_SCALE</code>.
	 */
	public Integer getNumericScale() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.DATETIME_PRECISION</code>.
	 */
	public void setDatetimePrecision(ULong value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.DATETIME_PRECISION</code>.
	 */
	public ULong getDatetimePrecision() {
		return (ULong) getValue(10);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.CHARACTER_SET_NAME</code>.
	 */
	public void setCharacterSetName(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.CHARACTER_SET_NAME</code>.
	 */
	public String getCharacterSetName() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.COLLATION_NAME</code>.
	 */
	public void setCollationName(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.COLLATION_NAME</code>.
	 */
	public String getCollationName() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.DTD_IDENTIFIER</code>.
	 */
	public void setDtdIdentifier(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.DTD_IDENTIFIER</code>.
	 */
	public String getDtdIdentifier() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.ROUTINE_BODY</code>.
	 */
	public void setRoutineBody(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.ROUTINE_BODY</code>.
	 */
	public String getRoutineBody() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.ROUTINE_DEFINITION</code>.
	 */
	public void setRoutineDefinition(String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.ROUTINE_DEFINITION</code>.
	 */
	public String getRoutineDefinition() {
		return (String) getValue(15);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.EXTERNAL_NAME</code>.
	 */
	public void setExternalName(String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.EXTERNAL_NAME</code>.
	 */
	public String getExternalName() {
		return (String) getValue(16);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.EXTERNAL_LANGUAGE</code>.
	 */
	public void setExternalLanguage(String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.EXTERNAL_LANGUAGE</code>.
	 */
	public String getExternalLanguage() {
		return (String) getValue(17);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.PARAMETER_STYLE</code>.
	 */
	public void setParameterStyle(String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.PARAMETER_STYLE</code>.
	 */
	public String getParameterStyle() {
		return (String) getValue(18);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.IS_DETERMINISTIC</code>.
	 */
	public void setIsDeterministic(String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.IS_DETERMINISTIC</code>.
	 */
	public String getIsDeterministic() {
		return (String) getValue(19);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.SQL_DATA_ACCESS</code>.
	 */
	public void setSqlDataAccess(String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.SQL_DATA_ACCESS</code>.
	 */
	public String getSqlDataAccess() {
		return (String) getValue(20);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.SQL_PATH</code>.
	 */
	public void setSqlPath(String value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.SQL_PATH</code>.
	 */
	public String getSqlPath() {
		return (String) getValue(21);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.SECURITY_TYPE</code>.
	 */
	public void setSecurityType(String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.SECURITY_TYPE</code>.
	 */
	public String getSecurityType() {
		return (String) getValue(22);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.CREATED</code>.
	 */
	public void setCreated(Timestamp value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.CREATED</code>.
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(23);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.LAST_ALTERED</code>.
	 */
	public void setLastAltered(Timestamp value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.LAST_ALTERED</code>.
	 */
	public Timestamp getLastAltered() {
		return (Timestamp) getValue(24);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.SQL_MODE</code>.
	 */
	public void setSqlMode(String value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.SQL_MODE</code>.
	 */
	public String getSqlMode() {
		return (String) getValue(25);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.ROUTINE_COMMENT</code>.
	 */
	public void setRoutineComment(String value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.ROUTINE_COMMENT</code>.
	 */
	public String getRoutineComment() {
		return (String) getValue(26);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.DEFINER</code>.
	 */
	public void setDefiner(String value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.DEFINER</code>.
	 */
	public String getDefiner() {
		return (String) getValue(27);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.CHARACTER_SET_CLIENT</code>.
	 */
	public void setCharacterSetClient(String value) {
		setValue(28, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.CHARACTER_SET_CLIENT</code>.
	 */
	public String getCharacterSetClient() {
		return (String) getValue(28);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.COLLATION_CONNECTION</code>.
	 */
	public void setCollationConnection(String value) {
		setValue(29, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.COLLATION_CONNECTION</code>.
	 */
	public String getCollationConnection() {
		return (String) getValue(29);
	}

	/**
	 * Setter for <code>information_schema.ROUTINES.DATABASE_COLLATION</code>.
	 */
	public void setDatabaseCollation(String value) {
		setValue(30, value);
	}

	/**
	 * Getter for <code>information_schema.ROUTINES.DATABASE_COLLATION</code>.
	 */
	public String getDatabaseCollation() {
		return (String) getValue(30);
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RoutinesRecord
	 */
	public RoutinesRecord() {
		super(Routines.ROUTINES);
	}

	/**
	 * Create a detached, initialised RoutinesRecord
	 */
	public RoutinesRecord(String specificName, String routineCatalog, String routineSchema, String routineName, String routineType, String dataType, Integer characterMaximumLength, Integer characterOctetLength, ULong numericPrecision, Integer numericScale, ULong datetimePrecision, String characterSetName, String collationName, String dtdIdentifier, String routineBody, String routineDefinition, String externalName, String externalLanguage, String parameterStyle, String isDeterministic, String sqlDataAccess, String sqlPath, String securityType, Timestamp created, Timestamp lastAltered, String sqlMode, String routineComment, String definer, String characterSetClient, String collationConnection, String databaseCollation) {
		super(Routines.ROUTINES);

		setValue(0, specificName);
		setValue(1, routineCatalog);
		setValue(2, routineSchema);
		setValue(3, routineName);
		setValue(4, routineType);
		setValue(5, dataType);
		setValue(6, characterMaximumLength);
		setValue(7, characterOctetLength);
		setValue(8, numericPrecision);
		setValue(9, numericScale);
		setValue(10, datetimePrecision);
		setValue(11, characterSetName);
		setValue(12, collationName);
		setValue(13, dtdIdentifier);
		setValue(14, routineBody);
		setValue(15, routineDefinition);
		setValue(16, externalName);
		setValue(17, externalLanguage);
		setValue(18, parameterStyle);
		setValue(19, isDeterministic);
		setValue(20, sqlDataAccess);
		setValue(21, sqlPath);
		setValue(22, securityType);
		setValue(23, created);
		setValue(24, lastAltered);
		setValue(25, sqlMode);
		setValue(26, routineComment);
		setValue(27, definer);
		setValue(28, characterSetClient);
		setValue(29, collationConnection);
		setValue(30, databaseCollation);
	}
}
