/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.example.gradle.db.information_schema.InformationSchema;
import org.jooq.example.gradle.db.information_schema.tables.records.InnodbFtIndexTableRecord;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbFtIndexTable extends TableImpl<InnodbFtIndexTableRecord> {

	private static final long serialVersionUID = 1806921910;

	/**
	 * The reference instance of <code>information_schema.INNODB_FT_INDEX_TABLE</code>
	 */
	public static final InnodbFtIndexTable INNODB_FT_INDEX_TABLE = new InnodbFtIndexTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<InnodbFtIndexTableRecord> getRecordType() {
		return InnodbFtIndexTableRecord.class;
	}

	/**
	 * The column <code>information_schema.INNODB_FT_INDEX_TABLE.WORD</code>.
	 */
	public final TableField<InnodbFtIndexTableRecord, String> WORD = createField("WORD", org.jooq.impl.SQLDataType.VARCHAR.length(337).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.INNODB_FT_INDEX_TABLE.FIRST_DOC_ID</code>.
	 */
	public final TableField<InnodbFtIndexTableRecord, ULong> FIRST_DOC_ID = createField("FIRST_DOC_ID", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.INNODB_FT_INDEX_TABLE.LAST_DOC_ID</code>.
	 */
	public final TableField<InnodbFtIndexTableRecord, ULong> LAST_DOC_ID = createField("LAST_DOC_ID", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.INNODB_FT_INDEX_TABLE.DOC_COUNT</code>.
	 */
	public final TableField<InnodbFtIndexTableRecord, ULong> DOC_COUNT = createField("DOC_COUNT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.INNODB_FT_INDEX_TABLE.DOC_ID</code>.
	 */
	public final TableField<InnodbFtIndexTableRecord, ULong> DOC_ID = createField("DOC_ID", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.INNODB_FT_INDEX_TABLE.POSITION</code>.
	 */
	public final TableField<InnodbFtIndexTableRecord, ULong> POSITION = createField("POSITION", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>information_schema.INNODB_FT_INDEX_TABLE</code> table reference
	 */
	public InnodbFtIndexTable() {
		this("INNODB_FT_INDEX_TABLE", null);
	}

	/**
	 * Create an aliased <code>information_schema.INNODB_FT_INDEX_TABLE</code> table reference
	 */
	public InnodbFtIndexTable(String alias) {
		this(alias, INNODB_FT_INDEX_TABLE);
	}

	private InnodbFtIndexTable(String alias, Table<InnodbFtIndexTableRecord> aliased) {
		this(alias, aliased, null);
	}

	private InnodbFtIndexTable(String alias, Table<InnodbFtIndexTableRecord> aliased, Field<?>[] parameters) {
		super(alias, InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InnodbFtIndexTable as(String alias) {
		return new InnodbFtIndexTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public InnodbFtIndexTable rename(String name) {
		return new InnodbFtIndexTable(name, null);
	}
}
