/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.example.gradle.db.information_schema.InformationSchema;
import org.jooq.example.gradle.db.information_schema.tables.records.InnodbFtConfigRecord;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbFtConfig extends TableImpl<InnodbFtConfigRecord> {

	private static final long serialVersionUID = 559928709;

	/**
	 * The reference instance of <code>information_schema.INNODB_FT_CONFIG</code>
	 */
	public static final InnodbFtConfig INNODB_FT_CONFIG = new InnodbFtConfig();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<InnodbFtConfigRecord> getRecordType() {
		return InnodbFtConfigRecord.class;
	}

	/**
	 * The column <code>information_schema.INNODB_FT_CONFIG.KEY</code>.
	 */
	public final TableField<InnodbFtConfigRecord, String> KEY = createField("KEY", org.jooq.impl.SQLDataType.VARCHAR.length(193).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.INNODB_FT_CONFIG.VALUE</code>.
	 */
	public final TableField<InnodbFtConfigRecord, String> VALUE = createField("VALUE", org.jooq.impl.SQLDataType.VARCHAR.length(193).nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>information_schema.INNODB_FT_CONFIG</code> table reference
	 */
	public InnodbFtConfig() {
		this("INNODB_FT_CONFIG", null);
	}

	/**
	 * Create an aliased <code>information_schema.INNODB_FT_CONFIG</code> table reference
	 */
	public InnodbFtConfig(String alias) {
		this(alias, INNODB_FT_CONFIG);
	}

	private InnodbFtConfig(String alias, Table<InnodbFtConfigRecord> aliased) {
		this(alias, aliased, null);
	}

	private InnodbFtConfig(String alias, Table<InnodbFtConfigRecord> aliased, Field<?>[] parameters) {
		super(alias, InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InnodbFtConfig as(String alias) {
		return new InnodbFtConfig(alias, this);
	}

	/**
	 * Rename this table
	 */
	public InnodbFtConfig rename(String name) {
		return new InnodbFtConfig(name, null);
	}
}
