/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.example.gradle.db.information_schema.InformationSchema;
import org.jooq.example.gradle.db.information_schema.tables.records.InnodbCmpmemRecord;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbCmpmem extends TableImpl<InnodbCmpmemRecord> {

	private static final long serialVersionUID = -874174087;

	/**
	 * The reference instance of <code>information_schema.INNODB_CMPMEM</code>
	 */
	public static final InnodbCmpmem INNODB_CMPMEM = new InnodbCmpmem();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<InnodbCmpmemRecord> getRecordType() {
		return InnodbCmpmemRecord.class;
	}

	/**
	 * The column <code>information_schema.INNODB_CMPMEM.page_size</code>.
	 */
	public final TableField<InnodbCmpmemRecord, Integer> PAGE_SIZE = createField("page_size", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.INNODB_CMPMEM.buffer_pool_instance</code>.
	 */
	public final TableField<InnodbCmpmemRecord, Integer> BUFFER_POOL_INSTANCE = createField("buffer_pool_instance", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.INNODB_CMPMEM.pages_used</code>.
	 */
	public final TableField<InnodbCmpmemRecord, Integer> PAGES_USED = createField("pages_used", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.INNODB_CMPMEM.pages_free</code>.
	 */
	public final TableField<InnodbCmpmemRecord, Integer> PAGES_FREE = createField("pages_free", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.INNODB_CMPMEM.relocation_ops</code>.
	 */
	public final TableField<InnodbCmpmemRecord, Long> RELOCATION_OPS = createField("relocation_ops", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.INNODB_CMPMEM.relocation_time</code>.
	 */
	public final TableField<InnodbCmpmemRecord, Integer> RELOCATION_TIME = createField("relocation_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>information_schema.INNODB_CMPMEM</code> table reference
	 */
	public InnodbCmpmem() {
		this("INNODB_CMPMEM", null);
	}

	/**
	 * Create an aliased <code>information_schema.INNODB_CMPMEM</code> table reference
	 */
	public InnodbCmpmem(String alias) {
		this(alias, INNODB_CMPMEM);
	}

	private InnodbCmpmem(String alias, Table<InnodbCmpmemRecord> aliased) {
		this(alias, aliased, null);
	}

	private InnodbCmpmem(String alias, Table<InnodbCmpmemRecord> aliased, Field<?>[] parameters) {
		super(alias, InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InnodbCmpmem as(String alias) {
		return new InnodbCmpmem(alias, this);
	}

	/**
	 * Rename this table
	 */
	public InnodbCmpmem rename(String name) {
		return new InnodbCmpmem(name, null);
	}
}
