/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.example.gradle.db.information_schema.InformationSchema;
import org.jooq.example.gradle.db.information_schema.tables.records.SchemaPrivilegesRecord;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemaPrivileges extends TableImpl<SchemaPrivilegesRecord> {

	private static final long serialVersionUID = 818484131;

	/**
	 * The reference instance of <code>information_schema.SCHEMA_PRIVILEGES</code>
	 */
	public static final SchemaPrivileges SCHEMA_PRIVILEGES = new SchemaPrivileges();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SchemaPrivilegesRecord> getRecordType() {
		return SchemaPrivilegesRecord.class;
	}

	/**
	 * The column <code>information_schema.SCHEMA_PRIVILEGES.GRANTEE</code>.
	 */
	public final TableField<SchemaPrivilegesRecord, String> GRANTEE = createField("GRANTEE", org.jooq.impl.SQLDataType.VARCHAR.length(81).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.SCHEMA_PRIVILEGES.TABLE_CATALOG</code>.
	 */
	public final TableField<SchemaPrivilegesRecord, String> TABLE_CATALOG = createField("TABLE_CATALOG", org.jooq.impl.SQLDataType.VARCHAR.length(512).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.SCHEMA_PRIVILEGES.TABLE_SCHEMA</code>.
	 */
	public final TableField<SchemaPrivilegesRecord, String> TABLE_SCHEMA = createField("TABLE_SCHEMA", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.SCHEMA_PRIVILEGES.PRIVILEGE_TYPE</code>.
	 */
	public final TableField<SchemaPrivilegesRecord, String> PRIVILEGE_TYPE = createField("PRIVILEGE_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.SCHEMA_PRIVILEGES.IS_GRANTABLE</code>.
	 */
	public final TableField<SchemaPrivilegesRecord, String> IS_GRANTABLE = createField("IS_GRANTABLE", org.jooq.impl.SQLDataType.VARCHAR.length(3).nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>information_schema.SCHEMA_PRIVILEGES</code> table reference
	 */
	public SchemaPrivileges() {
		this("SCHEMA_PRIVILEGES", null);
	}

	/**
	 * Create an aliased <code>information_schema.SCHEMA_PRIVILEGES</code> table reference
	 */
	public SchemaPrivileges(String alias) {
		this(alias, SCHEMA_PRIVILEGES);
	}

	private SchemaPrivileges(String alias, Table<SchemaPrivilegesRecord> aliased) {
		this(alias, aliased, null);
	}

	private SchemaPrivileges(String alias, Table<SchemaPrivilegesRecord> aliased, Field<?>[] parameters) {
		super(alias, InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemaPrivileges as(String alias) {
		return new SchemaPrivileges(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SchemaPrivileges rename(String name) {
		return new SchemaPrivileges(name, null);
	}
}
