/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.example.gradle.db.information_schema.InformationSchema;
import org.jooq.example.gradle.db.information_schema.tables.records.TablespacesRecord;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tablespaces extends TableImpl<TablespacesRecord> {

	private static final long serialVersionUID = -1358875445;

	/**
	 * The reference instance of <code>information_schema.TABLESPACES</code>
	 */
	public static final Tablespaces TABLESPACES = new Tablespaces();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TablespacesRecord> getRecordType() {
		return TablespacesRecord.class;
	}

	/**
	 * The column <code>information_schema.TABLESPACES.TABLESPACE_NAME</code>.
	 */
	public final TableField<TablespacesRecord, String> TABLESPACE_NAME = createField("TABLESPACE_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.TABLESPACES.ENGINE</code>.
	 */
	public final TableField<TablespacesRecord, String> ENGINE = createField("ENGINE", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.TABLESPACES.TABLESPACE_TYPE</code>.
	 */
	public final TableField<TablespacesRecord, String> TABLESPACE_TYPE = createField("TABLESPACE_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>information_schema.TABLESPACES.LOGFILE_GROUP_NAME</code>.
	 */
	public final TableField<TablespacesRecord, String> LOGFILE_GROUP_NAME = createField("LOGFILE_GROUP_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>information_schema.TABLESPACES.EXTENT_SIZE</code>.
	 */
	public final TableField<TablespacesRecord, ULong> EXTENT_SIZE = createField("EXTENT_SIZE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

	/**
	 * The column <code>information_schema.TABLESPACES.AUTOEXTEND_SIZE</code>.
	 */
	public final TableField<TablespacesRecord, ULong> AUTOEXTEND_SIZE = createField("AUTOEXTEND_SIZE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

	/**
	 * The column <code>information_schema.TABLESPACES.MAXIMUM_SIZE</code>.
	 */
	public final TableField<TablespacesRecord, ULong> MAXIMUM_SIZE = createField("MAXIMUM_SIZE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

	/**
	 * The column <code>information_schema.TABLESPACES.NODEGROUP_ID</code>.
	 */
	public final TableField<TablespacesRecord, ULong> NODEGROUP_ID = createField("NODEGROUP_ID", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

	/**
	 * The column <code>information_schema.TABLESPACES.TABLESPACE_COMMENT</code>.
	 */
	public final TableField<TablespacesRecord, String> TABLESPACE_COMMENT = createField("TABLESPACE_COMMENT", org.jooq.impl.SQLDataType.VARCHAR.length(2048), this, "");

	/**
	 * Create a <code>information_schema.TABLESPACES</code> table reference
	 */
	public Tablespaces() {
		this("TABLESPACES", null);
	}

	/**
	 * Create an aliased <code>information_schema.TABLESPACES</code> table reference
	 */
	public Tablespaces(String alias) {
		this(alias, TABLESPACES);
	}

	private Tablespaces(String alias, Table<TablespacesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tablespaces(String alias, Table<TablespacesRecord> aliased, Field<?>[] parameters) {
		super(alias, InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Tablespaces as(String alias) {
		return new Tablespaces(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Tablespaces rename(String name) {
		return new Tablespaces(name, null);
	}
}
