/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.example.gradle.db.information_schema.InformationSchema;
import org.jooq.example.gradle.db.information_schema.tables.records.TablePrivilegesRecord;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TablePrivileges extends TableImpl<TablePrivilegesRecord> {

	private static final long serialVersionUID = 94549412;

	/**
	 * The reference instance of <code>information_schema.TABLE_PRIVILEGES</code>
	 */
	public static final TablePrivileges TABLE_PRIVILEGES = new TablePrivileges();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TablePrivilegesRecord> getRecordType() {
		return TablePrivilegesRecord.class;
	}

	/**
	 * The column <code>information_schema.TABLE_PRIVILEGES.GRANTEE</code>.
	 */
	public final TableField<TablePrivilegesRecord, String> GRANTEE = createField("GRANTEE", org.jooq.impl.SQLDataType.VARCHAR.length(81).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.TABLE_PRIVILEGES.TABLE_CATALOG</code>.
	 */
	public final TableField<TablePrivilegesRecord, String> TABLE_CATALOG = createField("TABLE_CATALOG", org.jooq.impl.SQLDataType.VARCHAR.length(512).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.TABLE_PRIVILEGES.TABLE_SCHEMA</code>.
	 */
	public final TableField<TablePrivilegesRecord, String> TABLE_SCHEMA = createField("TABLE_SCHEMA", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.TABLE_PRIVILEGES.TABLE_NAME</code>.
	 */
	public final TableField<TablePrivilegesRecord, String> TABLE_NAME = createField("TABLE_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.TABLE_PRIVILEGES.PRIVILEGE_TYPE</code>.
	 */
	public final TableField<TablePrivilegesRecord, String> PRIVILEGE_TYPE = createField("PRIVILEGE_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>information_schema.TABLE_PRIVILEGES.IS_GRANTABLE</code>.
	 */
	public final TableField<TablePrivilegesRecord, String> IS_GRANTABLE = createField("IS_GRANTABLE", org.jooq.impl.SQLDataType.VARCHAR.length(3).nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>information_schema.TABLE_PRIVILEGES</code> table reference
	 */
	public TablePrivileges() {
		this("TABLE_PRIVILEGES", null);
	}

	/**
	 * Create an aliased <code>information_schema.TABLE_PRIVILEGES</code> table reference
	 */
	public TablePrivileges(String alias) {
		this(alias, TABLE_PRIVILEGES);
	}

	private TablePrivileges(String alias, Table<TablePrivilegesRecord> aliased) {
		this(alias, aliased, null);
	}

	private TablePrivileges(String alias, Table<TablePrivilegesRecord> aliased, Field<?>[] parameters) {
		super(alias, InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TablePrivileges as(String alias) {
		return new TablePrivileges(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TablePrivileges rename(String name) {
		return new TablePrivileges(name, null);
	}
}
