/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollationCharacterSetApplicability implements Serializable {

	private static final long serialVersionUID = -896536296;

	private String collationName;
	private String characterSetName;

	public CollationCharacterSetApplicability() {}

	public CollationCharacterSetApplicability(CollationCharacterSetApplicability value) {
		this.collationName = value.collationName;
		this.characterSetName = value.characterSetName;
	}

	public CollationCharacterSetApplicability(
		String collationName,
		String characterSetName
	) {
		this.collationName = collationName;
		this.characterSetName = characterSetName;
	}

	public String getCollationName() {
		return this.collationName;
	}

	public void setCollationName(String collationName) {
		this.collationName = collationName;
	}

	public String getCharacterSetName() {
		return this.characterSetName;
	}

	public void setCharacterSetName(String characterSetName) {
		this.characterSetName = characterSetName;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("CollationCharacterSetApplicability (");

		sb.append(collationName);
		sb.append(", ").append(characterSetName);

		sb.append(")");
		return sb.toString();
	}
}
