/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Collations implements Serializable {

	private static final long serialVersionUID = -138531358;

	private String collationName;
	private String characterSetName;
	private Long   id;
	private String isDefault;
	private String isCompiled;
	private Long   sortlen;

	public Collations() {}

	public Collations(Collations value) {
		this.collationName = value.collationName;
		this.characterSetName = value.characterSetName;
		this.id = value.id;
		this.isDefault = value.isDefault;
		this.isCompiled = value.isCompiled;
		this.sortlen = value.sortlen;
	}

	public Collations(
		String collationName,
		String characterSetName,
		Long   id,
		String isDefault,
		String isCompiled,
		Long   sortlen
	) {
		this.collationName = collationName;
		this.characterSetName = characterSetName;
		this.id = id;
		this.isDefault = isDefault;
		this.isCompiled = isCompiled;
		this.sortlen = sortlen;
	}

	public String getCollationName() {
		return this.collationName;
	}

	public void setCollationName(String collationName) {
		this.collationName = collationName;
	}

	public String getCharacterSetName() {
		return this.characterSetName;
	}

	public void setCharacterSetName(String characterSetName) {
		this.characterSetName = characterSetName;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(String isDefault) {
		this.isDefault = isDefault;
	}

	public String getIsCompiled() {
		return this.isCompiled;
	}

	public void setIsCompiled(String isCompiled) {
		this.isCompiled = isCompiled;
	}

	public Long getSortlen() {
		return this.sortlen;
	}

	public void setSortlen(Long sortlen) {
		this.sortlen = sortlen;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Collations (");

		sb.append(collationName);
		sb.append(", ").append(characterSetName);
		sb.append(", ").append(id);
		sb.append(", ").append(isDefault);
		sb.append(", ").append(isCompiled);
		sb.append(", ").append(sortlen);

		sb.append(")");
		return sb.toString();
	}
}
