/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbSysIndexes implements Serializable {

	private static final long serialVersionUID = 767537790;

	private ULong   indexId;
	private String  name;
	private ULong   tableId;
	private Integer type;
	private Integer nFields;
	private Integer pageNo;
	private Integer space;
	private Integer mergeThreshold;

	public InnodbSysIndexes() {}

	public InnodbSysIndexes(InnodbSysIndexes value) {
		this.indexId = value.indexId;
		this.name = value.name;
		this.tableId = value.tableId;
		this.type = value.type;
		this.nFields = value.nFields;
		this.pageNo = value.pageNo;
		this.space = value.space;
		this.mergeThreshold = value.mergeThreshold;
	}

	public InnodbSysIndexes(
		ULong   indexId,
		String  name,
		ULong   tableId,
		Integer type,
		Integer nFields,
		Integer pageNo,
		Integer space,
		Integer mergeThreshold
	) {
		this.indexId = indexId;
		this.name = name;
		this.tableId = tableId;
		this.type = type;
		this.nFields = nFields;
		this.pageNo = pageNo;
		this.space = space;
		this.mergeThreshold = mergeThreshold;
	}

	public ULong getIndexId() {
		return this.indexId;
	}

	public void setIndexId(ULong indexId) {
		this.indexId = indexId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public ULong getTableId() {
		return this.tableId;
	}

	public void setTableId(ULong tableId) {
		this.tableId = tableId;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getNFields() {
		return this.nFields;
	}

	public void setNFields(Integer nFields) {
		this.nFields = nFields;
	}

	public Integer getPageNo() {
		return this.pageNo;
	}

	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}

	public Integer getSpace() {
		return this.space;
	}

	public void setSpace(Integer space) {
		this.space = space;
	}

	public Integer getMergeThreshold() {
		return this.mergeThreshold;
	}

	public void setMergeThreshold(Integer mergeThreshold) {
		this.mergeThreshold = mergeThreshold;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("InnodbSysIndexes (");

		sb.append(indexId);
		sb.append(", ").append(name);
		sb.append(", ").append(tableId);
		sb.append(", ").append(type);
		sb.append(", ").append(nFields);
		sb.append(", ").append(pageNo);
		sb.append(", ").append(space);
		sb.append(", ").append(mergeThreshold);

		sb.append(")");
		return sb.toString();
	}
}
