/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbLocks implements Serializable {

	private static final long serialVersionUID = 1437441289;

	private String lockId;
	private String lockTrxId;
	private String lockMode;
	private String lockType;
	private String lockTable;
	private String lockIndex;
	private ULong  lockSpace;
	private ULong  lockPage;
	private ULong  lockRec;
	private String lockData;

	public InnodbLocks() {}

	public InnodbLocks(InnodbLocks value) {
		this.lockId = value.lockId;
		this.lockTrxId = value.lockTrxId;
		this.lockMode = value.lockMode;
		this.lockType = value.lockType;
		this.lockTable = value.lockTable;
		this.lockIndex = value.lockIndex;
		this.lockSpace = value.lockSpace;
		this.lockPage = value.lockPage;
		this.lockRec = value.lockRec;
		this.lockData = value.lockData;
	}

	public InnodbLocks(
		String lockId,
		String lockTrxId,
		String lockMode,
		String lockType,
		String lockTable,
		String lockIndex,
		ULong  lockSpace,
		ULong  lockPage,
		ULong  lockRec,
		String lockData
	) {
		this.lockId = lockId;
		this.lockTrxId = lockTrxId;
		this.lockMode = lockMode;
		this.lockType = lockType;
		this.lockTable = lockTable;
		this.lockIndex = lockIndex;
		this.lockSpace = lockSpace;
		this.lockPage = lockPage;
		this.lockRec = lockRec;
		this.lockData = lockData;
	}

	public String getLockId() {
		return this.lockId;
	}

	public void setLockId(String lockId) {
		this.lockId = lockId;
	}

	public String getLockTrxId() {
		return this.lockTrxId;
	}

	public void setLockTrxId(String lockTrxId) {
		this.lockTrxId = lockTrxId;
	}

	public String getLockMode() {
		return this.lockMode;
	}

	public void setLockMode(String lockMode) {
		this.lockMode = lockMode;
	}

	public String getLockType() {
		return this.lockType;
	}

	public void setLockType(String lockType) {
		this.lockType = lockType;
	}

	public String getLockTable() {
		return this.lockTable;
	}

	public void setLockTable(String lockTable) {
		this.lockTable = lockTable;
	}

	public String getLockIndex() {
		return this.lockIndex;
	}

	public void setLockIndex(String lockIndex) {
		this.lockIndex = lockIndex;
	}

	public ULong getLockSpace() {
		return this.lockSpace;
	}

	public void setLockSpace(ULong lockSpace) {
		this.lockSpace = lockSpace;
	}

	public ULong getLockPage() {
		return this.lockPage;
	}

	public void setLockPage(ULong lockPage) {
		this.lockPage = lockPage;
	}

	public ULong getLockRec() {
		return this.lockRec;
	}

	public void setLockRec(ULong lockRec) {
		this.lockRec = lockRec;
	}

	public String getLockData() {
		return this.lockData;
	}

	public void setLockData(String lockData) {
		this.lockData = lockData;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("InnodbLocks (");

		sb.append(lockId);
		sb.append(", ").append(lockTrxId);
		sb.append(", ").append(lockMode);
		sb.append(", ").append(lockType);
		sb.append(", ").append(lockTable);
		sb.append(", ").append(lockIndex);
		sb.append(", ").append(lockSpace);
		sb.append(", ").append(lockPage);
		sb.append(", ").append(lockRec);
		sb.append(", ").append(lockData);

		sb.append(")");
		return sb.toString();
	}
}
