/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbSysTablestats implements Serializable {

	private static final long serialVersionUID = 712225065;

	private ULong   tableId;
	private String  name;
	private String  statsInitialized;
	private ULong   numRows;
	private ULong   clustIndexSize;
	private ULong   otherIndexSize;
	private ULong   modifiedCounter;
	private ULong   autoinc;
	private Integer refCount;

	public InnodbSysTablestats() {}

	public InnodbSysTablestats(InnodbSysTablestats value) {
		this.tableId = value.tableId;
		this.name = value.name;
		this.statsInitialized = value.statsInitialized;
		this.numRows = value.numRows;
		this.clustIndexSize = value.clustIndexSize;
		this.otherIndexSize = value.otherIndexSize;
		this.modifiedCounter = value.modifiedCounter;
		this.autoinc = value.autoinc;
		this.refCount = value.refCount;
	}

	public InnodbSysTablestats(
		ULong   tableId,
		String  name,
		String  statsInitialized,
		ULong   numRows,
		ULong   clustIndexSize,
		ULong   otherIndexSize,
		ULong   modifiedCounter,
		ULong   autoinc,
		Integer refCount
	) {
		this.tableId = tableId;
		this.name = name;
		this.statsInitialized = statsInitialized;
		this.numRows = numRows;
		this.clustIndexSize = clustIndexSize;
		this.otherIndexSize = otherIndexSize;
		this.modifiedCounter = modifiedCounter;
		this.autoinc = autoinc;
		this.refCount = refCount;
	}

	public ULong getTableId() {
		return this.tableId;
	}

	public void setTableId(ULong tableId) {
		this.tableId = tableId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStatsInitialized() {
		return this.statsInitialized;
	}

	public void setStatsInitialized(String statsInitialized) {
		this.statsInitialized = statsInitialized;
	}

	public ULong getNumRows() {
		return this.numRows;
	}

	public void setNumRows(ULong numRows) {
		this.numRows = numRows;
	}

	public ULong getClustIndexSize() {
		return this.clustIndexSize;
	}

	public void setClustIndexSize(ULong clustIndexSize) {
		this.clustIndexSize = clustIndexSize;
	}

	public ULong getOtherIndexSize() {
		return this.otherIndexSize;
	}

	public void setOtherIndexSize(ULong otherIndexSize) {
		this.otherIndexSize = otherIndexSize;
	}

	public ULong getModifiedCounter() {
		return this.modifiedCounter;
	}

	public void setModifiedCounter(ULong modifiedCounter) {
		this.modifiedCounter = modifiedCounter;
	}

	public ULong getAutoinc() {
		return this.autoinc;
	}

	public void setAutoinc(ULong autoinc) {
		this.autoinc = autoinc;
	}

	public Integer getRefCount() {
		return this.refCount;
	}

	public void setRefCount(Integer refCount) {
		this.refCount = refCount;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("InnodbSysTablestats (");

		sb.append(tableId);
		sb.append(", ").append(name);
		sb.append(", ").append(statsInitialized);
		sb.append(", ").append(numRows);
		sb.append(", ").append(clustIndexSize);
		sb.append(", ").append(otherIndexSize);
		sb.append(", ").append(modifiedCounter);
		sb.append(", ").append(autoinc);
		sb.append(", ").append(refCount);

		sb.append(")");
		return sb.toString();
	}
}
