/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbSysFields implements Serializable {

	private static final long serialVersionUID = 835294541;

	private ULong    indexId;
	private String   name;
	private UInteger pos;

	public InnodbSysFields() {}

	public InnodbSysFields(InnodbSysFields value) {
		this.indexId = value.indexId;
		this.name = value.name;
		this.pos = value.pos;
	}

	public InnodbSysFields(
		ULong    indexId,
		String   name,
		UInteger pos
	) {
		this.indexId = indexId;
		this.name = name;
		this.pos = pos;
	}

	public ULong getIndexId() {
		return this.indexId;
	}

	public void setIndexId(ULong indexId) {
		this.indexId = indexId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public UInteger getPos() {
		return this.pos;
	}

	public void setPos(UInteger pos) {
		this.pos = pos;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("InnodbSysFields (");

		sb.append(indexId);
		sb.append(", ").append(name);
		sb.append(", ").append(pos);

		sb.append(")");
		return sb.toString();
	}
}
