/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbSysTables implements Serializable {

	private static final long serialVersionUID = -1875405347;

	private ULong    tableId;
	private String   name;
	private Integer  flag;
	private Integer  nCols;
	private Integer  space;
	private String   fileFormat;
	private String   rowFormat;
	private UInteger zipPageSize;
	private String   spaceType;

	public InnodbSysTables() {}

	public InnodbSysTables(InnodbSysTables value) {
		this.tableId = value.tableId;
		this.name = value.name;
		this.flag = value.flag;
		this.nCols = value.nCols;
		this.space = value.space;
		this.fileFormat = value.fileFormat;
		this.rowFormat = value.rowFormat;
		this.zipPageSize = value.zipPageSize;
		this.spaceType = value.spaceType;
	}

	public InnodbSysTables(
		ULong    tableId,
		String   name,
		Integer  flag,
		Integer  nCols,
		Integer  space,
		String   fileFormat,
		String   rowFormat,
		UInteger zipPageSize,
		String   spaceType
	) {
		this.tableId = tableId;
		this.name = name;
		this.flag = flag;
		this.nCols = nCols;
		this.space = space;
		this.fileFormat = fileFormat;
		this.rowFormat = rowFormat;
		this.zipPageSize = zipPageSize;
		this.spaceType = spaceType;
	}

	public ULong getTableId() {
		return this.tableId;
	}

	public void setTableId(ULong tableId) {
		this.tableId = tableId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	public Integer getNCols() {
		return this.nCols;
	}

	public void setNCols(Integer nCols) {
		this.nCols = nCols;
	}

	public Integer getSpace() {
		return this.space;
	}

	public void setSpace(Integer space) {
		this.space = space;
	}

	public String getFileFormat() {
		return this.fileFormat;
	}

	public void setFileFormat(String fileFormat) {
		this.fileFormat = fileFormat;
	}

	public String getRowFormat() {
		return this.rowFormat;
	}

	public void setRowFormat(String rowFormat) {
		this.rowFormat = rowFormat;
	}

	public UInteger getZipPageSize() {
		return this.zipPageSize;
	}

	public void setZipPageSize(UInteger zipPageSize) {
		this.zipPageSize = zipPageSize;
	}

	public String getSpaceType() {
		return this.spaceType;
	}

	public void setSpaceType(String spaceType) {
		this.spaceType = spaceType;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("InnodbSysTables (");

		sb.append(tableId);
		sb.append(", ").append(name);
		sb.append(", ").append(flag);
		sb.append(", ").append(nCols);
		sb.append(", ").append(space);
		sb.append(", ").append(fileFormat);
		sb.append(", ").append(rowFormat);
		sb.append(", ").append(zipPageSize);
		sb.append(", ").append(spaceType);

		sb.append(")");
		return sb.toString();
	}
}
