/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbLockWaits implements Serializable {

	private static final long serialVersionUID = -1280065773;

	private String requestingTrxId;
	private String requestedLockId;
	private String blockingTrxId;
	private String blockingLockId;

	public InnodbLockWaits() {}

	public InnodbLockWaits(InnodbLockWaits value) {
		this.requestingTrxId = value.requestingTrxId;
		this.requestedLockId = value.requestedLockId;
		this.blockingTrxId = value.blockingTrxId;
		this.blockingLockId = value.blockingLockId;
	}

	public InnodbLockWaits(
		String requestingTrxId,
		String requestedLockId,
		String blockingTrxId,
		String blockingLockId
	) {
		this.requestingTrxId = requestingTrxId;
		this.requestedLockId = requestedLockId;
		this.blockingTrxId = blockingTrxId;
		this.blockingLockId = blockingLockId;
	}

	public String getRequestingTrxId() {
		return this.requestingTrxId;
	}

	public void setRequestingTrxId(String requestingTrxId) {
		this.requestingTrxId = requestingTrxId;
	}

	public String getRequestedLockId() {
		return this.requestedLockId;
	}

	public void setRequestedLockId(String requestedLockId) {
		this.requestedLockId = requestedLockId;
	}

	public String getBlockingTrxId() {
		return this.blockingTrxId;
	}

	public void setBlockingTrxId(String blockingTrxId) {
		this.blockingTrxId = blockingTrxId;
	}

	public String getBlockingLockId() {
		return this.blockingLockId;
	}

	public void setBlockingLockId(String blockingLockId) {
		this.blockingLockId = blockingLockId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("InnodbLockWaits (");

		sb.append(requestingTrxId);
		sb.append(", ").append(requestedLockId);
		sb.append(", ").append(blockingTrxId);
		sb.append(", ").append(blockingLockId);

		sb.append(")");
		return sb.toString();
	}
}
