/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Plugins implements Serializable {

	private static final long serialVersionUID = -1419881579;

	private String pluginName;
	private String pluginVersion;
	private String pluginStatus;
	private String pluginType;
	private String pluginTypeVersion;
	private String pluginLibrary;
	private String pluginLibraryVersion;
	private String pluginAuthor;
	private String pluginDescription;
	private String pluginLicense;
	private String loadOption;

	public Plugins() {}

	public Plugins(Plugins value) {
		this.pluginName = value.pluginName;
		this.pluginVersion = value.pluginVersion;
		this.pluginStatus = value.pluginStatus;
		this.pluginType = value.pluginType;
		this.pluginTypeVersion = value.pluginTypeVersion;
		this.pluginLibrary = value.pluginLibrary;
		this.pluginLibraryVersion = value.pluginLibraryVersion;
		this.pluginAuthor = value.pluginAuthor;
		this.pluginDescription = value.pluginDescription;
		this.pluginLicense = value.pluginLicense;
		this.loadOption = value.loadOption;
	}

	public Plugins(
		String pluginName,
		String pluginVersion,
		String pluginStatus,
		String pluginType,
		String pluginTypeVersion,
		String pluginLibrary,
		String pluginLibraryVersion,
		String pluginAuthor,
		String pluginDescription,
		String pluginLicense,
		String loadOption
	) {
		this.pluginName = pluginName;
		this.pluginVersion = pluginVersion;
		this.pluginStatus = pluginStatus;
		this.pluginType = pluginType;
		this.pluginTypeVersion = pluginTypeVersion;
		this.pluginLibrary = pluginLibrary;
		this.pluginLibraryVersion = pluginLibraryVersion;
		this.pluginAuthor = pluginAuthor;
		this.pluginDescription = pluginDescription;
		this.pluginLicense = pluginLicense;
		this.loadOption = loadOption;
	}

	public String getPluginName() {
		return this.pluginName;
	}

	public void setPluginName(String pluginName) {
		this.pluginName = pluginName;
	}

	public String getPluginVersion() {
		return this.pluginVersion;
	}

	public void setPluginVersion(String pluginVersion) {
		this.pluginVersion = pluginVersion;
	}

	public String getPluginStatus() {
		return this.pluginStatus;
	}

	public void setPluginStatus(String pluginStatus) {
		this.pluginStatus = pluginStatus;
	}

	public String getPluginType() {
		return this.pluginType;
	}

	public void setPluginType(String pluginType) {
		this.pluginType = pluginType;
	}

	public String getPluginTypeVersion() {
		return this.pluginTypeVersion;
	}

	public void setPluginTypeVersion(String pluginTypeVersion) {
		this.pluginTypeVersion = pluginTypeVersion;
	}

	public String getPluginLibrary() {
		return this.pluginLibrary;
	}

	public void setPluginLibrary(String pluginLibrary) {
		this.pluginLibrary = pluginLibrary;
	}

	public String getPluginLibraryVersion() {
		return this.pluginLibraryVersion;
	}

	public void setPluginLibraryVersion(String pluginLibraryVersion) {
		this.pluginLibraryVersion = pluginLibraryVersion;
	}

	public String getPluginAuthor() {
		return this.pluginAuthor;
	}

	public void setPluginAuthor(String pluginAuthor) {
		this.pluginAuthor = pluginAuthor;
	}

	public String getPluginDescription() {
		return this.pluginDescription;
	}

	public void setPluginDescription(String pluginDescription) {
		this.pluginDescription = pluginDescription;
	}

	public String getPluginLicense() {
		return this.pluginLicense;
	}

	public void setPluginLicense(String pluginLicense) {
		this.pluginLicense = pluginLicense;
	}

	public String getLoadOption() {
		return this.loadOption;
	}

	public void setLoadOption(String loadOption) {
		this.loadOption = loadOption;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Plugins (");

		sb.append(pluginName);
		sb.append(", ").append(pluginVersion);
		sb.append(", ").append(pluginStatus);
		sb.append(", ").append(pluginType);
		sb.append(", ").append(pluginTypeVersion);
		sb.append(", ").append(pluginLibrary);
		sb.append(", ").append(pluginLibraryVersion);
		sb.append(", ").append(pluginAuthor);
		sb.append(", ").append(pluginDescription);
		sb.append(", ").append(pluginLicense);
		sb.append(", ").append(loadOption);

		sb.append(")");
		return sb.toString();
	}
}
