/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemaPrivileges implements Serializable {

	private static final long serialVersionUID = -651965222;

	private String grantee;
	private String tableCatalog;
	private String tableSchema;
	private String privilegeType;
	private String isGrantable;

	public SchemaPrivileges() {}

	public SchemaPrivileges(SchemaPrivileges value) {
		this.grantee = value.grantee;
		this.tableCatalog = value.tableCatalog;
		this.tableSchema = value.tableSchema;
		this.privilegeType = value.privilegeType;
		this.isGrantable = value.isGrantable;
	}

	public SchemaPrivileges(
		String grantee,
		String tableCatalog,
		String tableSchema,
		String privilegeType,
		String isGrantable
	) {
		this.grantee = grantee;
		this.tableCatalog = tableCatalog;
		this.tableSchema = tableSchema;
		this.privilegeType = privilegeType;
		this.isGrantable = isGrantable;
	}

	public String getGrantee() {
		return this.grantee;
	}

	public void setGrantee(String grantee) {
		this.grantee = grantee;
	}

	public String getTableCatalog() {
		return this.tableCatalog;
	}

	public void setTableCatalog(String tableCatalog) {
		this.tableCatalog = tableCatalog;
	}

	public String getTableSchema() {
		return this.tableSchema;
	}

	public void setTableSchema(String tableSchema) {
		this.tableSchema = tableSchema;
	}

	public String getPrivilegeType() {
		return this.privilegeType;
	}

	public void setPrivilegeType(String privilegeType) {
		this.privilegeType = privilegeType;
	}

	public String getIsGrantable() {
		return this.isGrantable;
	}

	public void setIsGrantable(String isGrantable) {
		this.isGrantable = isGrantable;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("SchemaPrivileges (");

		sb.append(grantee);
		sb.append(", ").append(tableCatalog);
		sb.append(", ").append(tableSchema);
		sb.append(", ").append(privilegeType);
		sb.append(", ").append(isGrantable);

		sb.append(")");
		return sb.toString();
	}
}
